services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JBartels\BeAcl\:
    resource: '../Classes/*'

  TYPO3\CMS\Beuser\Controller\PermissionController:
    class: JBartels\BeAcl\Controller\PermissionController
    tags: ['backend.controller']
